version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: corona-crawler
      POSTGRES_USER: corona-user
      POSTGRES_PASSWORD: corona-password
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  crawler:
    image: ${DOCKER_IMAGE_TAG}
    ports:
      - "8080:8080"
    command:
      - /app/crawler

volumes:
  postgres-data:
